package com.example.terminal_control;

public class elDefinitions {
    public static final int MAX_BUFF = 8096;      //includes tcpip buffer
    public static final int MAXRXFRAMESize = 4096;
    public static final int STX1 = 0xAA;
    public static final int STX2 = 0x55;
    public static final int ETX = 0xF0;
    //Frame Receive State
    public static final int PollSourceID = 0x83;
    //Command list
    public static final int		cmdSetDateTime	=	0x50;
    public static final int		cmdGetDateTime	=	0x51;
    public static final int		cmdSetTerID		=	0x52;
    public static final int		cmdGetTerID		=	0x53;
    public static final int		cmdSetBLData	=	0x54;
    public static final int		cmdGetBLData	=	0x55;
    public static final int		cmdClrBLData	=	0x56;
    public static final int		cmdSetEACD		=	0x58;
    public static final int		cmdGetEACD		=	0x59;
    public static final int		cmdSetLockTime	=	0x5A;
    public static final int		cmdGetLockTime	=	0x5B;
    public static final int		cmdSetUnlockTime=	0x5C;
    public static final int		cmdGetUnlockTime=	0x5D;
    public static final int		cmdSetTerMode	=	0x5E;
    public static final int		cmdGetTerMode	=	0x5F;
    public static final int		cmdGetLogCount	=	0x60;
    public static final int		cmdGetLogData	=	0x61;
    public static final int		cmdDeleteLogs	=	0x63;
    public static final int		cmdSetDoorNo	=	0x65;
    public static final int		cmdGetDoorNo	=	0x66;
    public static final int		cmdGetBLCount	=	0x67;
    public static final int		cmdSetCustID	=	0x68;
    public static final int		cmdGetCustID	=	0x69;
    public static final int		cmdSetUpdateInOut=	0x6B;
    public static final int		cmdGetUpdateInOut=	0x6C;
    public static final int		cmdSetResTime	=	0x6D;
    public static final int		cmdGetResTime	=	0x6E;
    public static final int		cmdSetTerDir	=	0x6F;
    public static final int		cmdGetTerDir	=	0x70;
    public static final int		cmdGetLastModDateTime=	0x71;
    public static final int		cmdSetTimeSlots		=0x72;
    public static final int		cmdGetTimeSlots		=0x73;
    public static final int		cmdGetLogDataMC		=0x75;
    public static final int		cmdGetUBL			=0x76;			//Get Updated black list (Written to the Card)
    public static final int		cmdGetLogDataBio	=0x77;			//Delete, Get Log Count, and delete
    public static final int		cmdDirectBioCmd		=0x78;			//This command is to send direct command to Bio
    public static final int		cmdSetSiteNo		=0x79;
    public static final int		cmdGetSiteNo		=0x7A;
    public static final int		cmdRestartTer		=0x7B;			//Restart the terminal on line
    public static final int		cmdATPUpdate		=0x7C;
    public static final int		cmdATPCount			=0x7D;
    public static final int		cmdATPList			=0x7E;
    public static final int		cmdATPDelete		=0x7F;
    public static final int		cmdLoadDefaults		=0x80;
    public static final int		cmdSetEmerDoorOpen	=0x81;
    public static final int		cmdSetAuth			=0x84;
    public static final int		cmdGetAuth			=0x85;
    public static final int		cmdSetFpScore		=0x86;
    public static final int		cmdGetFpScore		=0x87;
    public static final int		cmdWhoAmI			=0x88;
    public static final int		cmdSetFpTmSlabs		=0x8F;
    public static final int		cmdGetFpTmSlabs		=0x90;
    public static final int		cmdSetTerName		=0x91;
    public static final int		cmdGetTerName		=0x92;
    public static final int		cmdSetETH			=0x93;
    public static final int		cmdGetETH			=0x94;
    public static final int		cmdSetTUL			=0x95;		//Set Terminal Unlock
    public static final int		cmdGetTUL			=0x96;		//Get Terminal Unlock
    public static final int		cmdSet_Sys_1K_4K	=0x97;
    public static final int		cmdGet_Sys_1K_4K	=0x98;
    public static final int		cmdSetPrepFirmwareUpgrade =0x99;
    public static final int        cmdSetTerBioType = 0x9A;
    public static final int        cmdGetTerBioType = 0x9B;
    public static final int		cmdGetRDR			=0xA0;
    public static final int        cmdSetRDR           = 0xA1;
    public static final int        cmdGetInputConfig   = 0xA6;
    public static final int        cmdSetInputConfig   = 0xA7;
    public static final int        cmdGetTerminalExtendedPara = 0xA8;
    public static final int        cmdSetTerminalExtendedPara = 0xA9;
    public static final int        cmdSetTerLockNormalMode = 0xAA;
    public static final int        cmdGetTerLockNormalMode = 0xAB;
    public static final int        cmdSetOutputConfig      = 0xAC;
    public static final int        cmdGetOutputConfig      = 0xAD;
    public static final int        cmdOperateOutputControl = 0xAE;
    public static final int        cmdGetepurseprintcnt = 0xB0;///////
    public static final int        cmdSetepurseprintcnt = 0xB1;///////
    public static final int        cmdSetACCGRP        = 0x9C;
    public static final int        cmdGetACCGRP        = 0x9D;
    public static final int        cmdSetACCSCH        = 0x9E;
    public static final int        cmdGetACCSCH        = 0x9F;
    public static final int        cmdGetHOLDAY        = 0xA2;
    public static final int        cmdSetHOLDAY        = 0xA3;
    public static final int        cmdSetAntipassbackZone = 0xA4;
    public static final int        cmdGetAntipassbackZone = 0xA5;
    public static final int        cmdGetDiagnostic    = 0xDF;
    public static final int        cmdOpenRLY2         = 0xDC;
    public static final int        cmdCloseRLY2        = 0xDD;
    public static final int        cmdOpenRLY3         = 0xE0;
    public static final int        cmdCloseRLY3        = 0xE1;
    public static final int        cmdFlashEraseLogs   = 0xE3;
    //added by pradeep
    public static final int		Valid_Log	=0x00;
    public static final int		AccessDenied =0x01;
    public static final int		LockErr		=0x02;
    public static final int		AccessDenied_LockError=0x03;
    public static final int		Antipassback_Error	=0x04;
    public static final int		CardExpired	=0x05;
    public static final int		CardExpired_AccessDenied=0x06;
    public static final int		BiometricFail	=0x07;
    public static final int		Access_withEscort	=0x09;
    public static final int		Access_duringholiday =0x0a;
    public static final int		Access_duringleave	=0x0b;
    public static final int        Cardtwining_record	= 0x0c;
    public static final int        PinFail        = 0x0f;
    public static final int        DoorForced_opened  = 0x10;
    public static final int        Doorkept_opened    = 0x11;
    public static final int        DoorOpened_bycommand = 0x12;
    public static final int        Dooropened_withEP = 0x13;
    public static final int        DoorOpened_withEMBU = 0x14;
    public static final int        PrepareFlashTimeout = 0x78; //120 Seconds

}
